version: "3"

services:
  nginx-app-01:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        - APP_DIR=01_app
        - UPSTREAM_NAME=localhost
        - FPM_PORT=9000
    image: ${TF_VAR_aws_account_id}.dkr.ecr.ap-northeast-1.amazonaws.com/fargate-${TF_VAR_project}-nginx-app-01
    ports:
      - "80:80"
    depends_on:
      - php-app-01

  php-app-01:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - APP_DIR=01_app
    image: ${TF_VAR_aws_account_id}.dkr.ecr.ap-northeast-1.amazonaws.com/fargate-${TF_VAR_project}-php-app-01
    ports:
      - "9000:9000"